import type { Carrier, RequiredDocumentName } from "@/types/carrier";

export const REQUIRED_DOCUMENTS: RequiredDocumentName[] = [
  "Certificate of Insurance",
  "W-9",
  "Operating Authority",
  "Drug & Alcohol Consortium",
  "Driver Qualification File",
  "MVR",
  "Medical Card",
  "CDL",
  "Annual Inspection",
  "Vehicle Registration",
  "Lease Agreement",
  "ELD setup confirmation",
];

export const mockCarriers: Carrier[] = [
  {
    id: "carrier-001",
    companyName: "Redline Freight Partners",
    mcNumber: "MC-812449",
    dotNumber: "DOT-2981440",
    contactName: "Marisol Grant",
    phone: "(312) 555-0174",
    email: "dispatch@redlinefreight.example",
    status: "Active",
    notes: "Strong renewal cadence. Insurance agent confirmed automatic COI updates for Manifest lanes.",
    documents: {
      "Certificate of Insurance": { uploaded: true, expirationDate: "2026-08-15" },
      "W-9": { uploaded: true, expirationDate: null },
      "Operating Authority": { uploaded: true, expirationDate: null },
      "Drug & Alcohol Consortium": { uploaded: true, expirationDate: "2026-10-01" },
      "Driver Qualification File": { uploaded: true, expirationDate: "2027-01-12" },
      MVR: { uploaded: true, expirationDate: "2026-06-07" },
      "Medical Card": { uploaded: true, expirationDate: "2026-09-30" },
      CDL: { uploaded: true, expirationDate: "2028-04-11" },
      "Annual Inspection": { uploaded: true, expirationDate: "2026-05-29" },
      "Vehicle Registration": { uploaded: true, expirationDate: "2026-12-31" },
      "Lease Agreement": { uploaded: true, expirationDate: "2027-03-10" },
      "ELD setup confirmation": { uploaded: true, expirationDate: null },
    },
  },
  {
    id: "carrier-002",
    companyName: "Iron Mile Transport",
    mcNumber: "MC-604182",
    dotNumber: "DOT-1855062",
    contactName: "Trevor Mills",
    phone: "(404) 555-0119",
    email: "compliance@ironmile.example",
    status: "Pending",
    notes: "New onboarding carrier. Missing lease agreement and ELD setup confirmation before dispatch approval.",
    documents: {
      "Certificate of Insurance": { uploaded: true, expirationDate: "2026-06-10" },
      "W-9": { uploaded: true, expirationDate: null },
      "Operating Authority": { uploaded: true, expirationDate: null },
      "Drug & Alcohol Consortium": { uploaded: true, expirationDate: "2026-07-04" },
      "Driver Qualification File": { uploaded: false, expirationDate: null },
      MVR: { uploaded: true, expirationDate: "2026-05-20" },
      "Medical Card": { uploaded: true, expirationDate: "2026-11-17" },
      CDL: { uploaded: true, expirationDate: "2027-08-21" },
      "Annual Inspection": { uploaded: true, expirationDate: "2026-06-15" },
      "Vehicle Registration": { uploaded: true, expirationDate: "2026-09-01" },
      "Lease Agreement": { uploaded: false, expirationDate: null },
      "ELD setup confirmation": { uploaded: false, expirationDate: null },
    },
  },
  {
    id: "carrier-003",
    companyName: "Northstar Linehaul",
    mcNumber: "MC-447019",
    dotNumber: "DOT-2298711",
    contactName: "Yara Chen",
    phone: "(206) 555-0142",
    email: "ops@northstarlinehaul.example",
    status: "Active",
    notes: "Audit-ready carrier. No open document gaps and responsive compliance contact.",
    documents: {
      "Certificate of Insurance": { uploaded: true, expirationDate: "2027-01-01" },
      "W-9": { uploaded: true, expirationDate: null },
      "Operating Authority": { uploaded: true, expirationDate: null },
      "Drug & Alcohol Consortium": { uploaded: true, expirationDate: "2027-02-20" },
      "Driver Qualification File": { uploaded: true, expirationDate: "2027-04-01" },
      MVR: { uploaded: true, expirationDate: "2026-10-14" },
      "Medical Card": { uploaded: true, expirationDate: "2027-06-19" },
      CDL: { uploaded: true, expirationDate: "2029-12-12" },
      "Annual Inspection": { uploaded: true, expirationDate: "2026-11-23" },
      "Vehicle Registration": { uploaded: true, expirationDate: "2027-01-31" },
      "Lease Agreement": { uploaded: true, expirationDate: "2027-02-01" },
      "ELD setup confirmation": { uploaded: true, expirationDate: null },
    },
  },
  {
    id: "carrier-004",
    companyName: "Summit Ridge Carriers",
    mcNumber: "MC-733820",
    dotNumber: "DOT-3149087",
    contactName: "Eli Romero",
    phone: "(602) 555-0188",
    email: "eli.romero@summitridge.example",
    status: "Suspended",
    notes: "Suspended after expired insurance and annual inspection. Require management review before reactivation.",
    documents: {
      "Certificate of Insurance": { uploaded: true, expirationDate: "2026-04-28" },
      "W-9": { uploaded: true, expirationDate: null },
      "Operating Authority": { uploaded: true, expirationDate: null },
      "Drug & Alcohol Consortium": { uploaded: true, expirationDate: "2026-05-01" },
      "Driver Qualification File": { uploaded: true, expirationDate: "2026-12-01" },
      MVR: { uploaded: false, expirationDate: null },
      "Medical Card": { uploaded: true, expirationDate: "2026-05-17" },
      CDL: { uploaded: true, expirationDate: "2027-04-04" },
      "Annual Inspection": { uploaded: true, expirationDate: "2026-03-22" },
      "Vehicle Registration": { uploaded: true, expirationDate: "2026-08-08" },
      "Lease Agreement": { uploaded: true, expirationDate: "2026-09-09" },
      "ELD setup confirmation": { uploaded: false, expirationDate: null },
    },
  },
  {
    id: "carrier-005",
    companyName: "Blue Harbor Logistics",
    mcNumber: "MC-921557",
    dotNumber: "DOT-3952021",
    contactName: "Nadia Brooks",
    phone: "(757) 555-0197",
    email: "carrierfiles@blueharbor.example",
    status: "Inactive",
    notes: "Inactive carrier retained for records. Needs updated MVR and operating package before new loads.",
    documents: {
      "Certificate of Insurance": { uploaded: true, expirationDate: "2026-12-01" },
      "W-9": { uploaded: true, expirationDate: null },
      "Operating Authority": { uploaded: true, expirationDate: null },
      "Drug & Alcohol Consortium": { uploaded: true, expirationDate: "2026-09-16" },
      "Driver Qualification File": { uploaded: true, expirationDate: "2026-07-19" },
      MVR: { uploaded: true, expirationDate: "2026-04-30" },
      "Medical Card": { uploaded: true, expirationDate: "2026-06-05" },
      CDL: { uploaded: true, expirationDate: "2028-06-03" },
      "Annual Inspection": { uploaded: false, expirationDate: null },
      "Vehicle Registration": { uploaded: true, expirationDate: "2026-10-22" },
      "Lease Agreement": { uploaded: true, expirationDate: "2027-01-14" },
      "ELD setup confirmation": { uploaded: true, expirationDate: null },
    },
  },
  {
    id: "carrier-006",
    companyName: "Keystone Express Group",
    mcNumber: "MC-105933",
    dotNumber: "DOT-1702944",
    contactName: "Priya Patel",
    phone: "(215) 555-0136",
    email: "safety@keystoneexpress.example",
    status: "Active",
    notes: "Reliable regional partner. Medical card and insurance are inside the 30-day renewal window.",
    documents: {
      "Certificate of Insurance": { uploaded: true, expirationDate: "2026-06-01" },
      "W-9": { uploaded: true, expirationDate: null },
      "Operating Authority": { uploaded: true, expirationDate: null },
      "Drug & Alcohol Consortium": { uploaded: true, expirationDate: "2026-08-12" },
      "Driver Qualification File": { uploaded: true, expirationDate: "2026-12-18" },
      MVR: { uploaded: true, expirationDate: "2026-06-26" },
      "Medical Card": { uploaded: true, expirationDate: "2026-05-30" },
      CDL: { uploaded: true, expirationDate: "2029-02-28" },
      "Annual Inspection": { uploaded: true, expirationDate: "2026-08-30" },
      "Vehicle Registration": { uploaded: true, expirationDate: "2026-09-30" },
      "Lease Agreement": { uploaded: true, expirationDate: "2027-02-15" },
      "ELD setup confirmation": { uploaded: true, expirationDate: null },
    },
  },
];
