"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const node_test_1 = __importDefault(require("node:test"));
const strict_1 = __importDefault(require("node:assert/strict"));
const tenant_rules_1 = require("../../lib/security/tenant-rules");
const orgA = "org-a";
const orgB = "org-b";
const carrierA = "carrier-a";
const carrierB = "carrier-b";
function session(overrides) {
    return Object.assign({ userId: "user-1", email: "user@example.test", fullName: "Test User", role: "carrier", organizationId: orgA, organizationName: "Org A", organizationSlug: "org-a", platformSuperAdmin: false, carrierId: null }, overrides);
}
(0, node_test_1.default)("organization access allows own active org and blocks other or suspended orgs", () => {
    const admin = session({ role: "admin" });
    strict_1.default.equal((0, tenant_rules_1.canAccessOrganizationRecord)(admin, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessOrganizationRecord)(admin, orgB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessOrganizationRecord)(admin, orgA, false), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessOrganizationRecord)(null, orgA, true), false);
});
(0, node_test_1.default)("platform super admin can access all organizations including suspended organizations", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    strict_1.default.equal((0, tenant_rules_1.canAccessOrganizationRecord)(platform, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessOrganizationRecord)(platform, orgB, false), true);
});
(0, node_test_1.default)("role permission checks match dashboard, carrier management, and compliance rules", () => {
    strict_1.default.equal((0, tenant_rules_1.canRoleAccessDashboard)("admin"), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleAccessDashboard)("staff"), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleAccessDashboard)("carrier"), false);
    strict_1.default.equal((0, tenant_rules_1.canRoleAccessDashboard)("carrier", true), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCarriers)("admin"), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCarriers)("staff"), false);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCarriers)("carrier"), false);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCarriers)("carrier", true), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCompliance)("admin"), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCompliance)("staff"), true);
    strict_1.default.equal((0, tenant_rules_1.canRoleManageCompliance)("carrier"), false);
});
(0, node_test_1.default)("carrier user can only access linked carrier in their active organization", () => {
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(carrierUser, { organizationId: orgA, carrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(carrierUser, { organizationId: orgB, carrierId: carrierA }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(carrierUser, { organizationId: orgA, carrierId: carrierA }, false), false);
});
(0, node_test_1.default)("linked carrier upload permission allows only own carrier document uploads", () => {
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(admin, { organizationId: orgA, carrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(staff, { organizationId: orgA, carrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(admin, { organizationId: orgB, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(staff, { organizationId: orgA, carrierId: carrierA }, false), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(carrierUser, { organizationId: orgA, carrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadCarrierDocument)(otherCarrierUser, { organizationId: orgB, carrierId: carrierB }, true), false);
});
(0, node_test_1.default)("vehicle document permission allows admins, staff, and linked carriers only", () => {
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    const equipmentA = { organizationId: orgA, carrierId: carrierA, equipmentId: "equipment-a" };
    strict_1.default.equal((0, tenant_rules_1.canManageEquipmentDocumentRecord)(admin, equipmentA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageEquipmentDocumentRecord)(staff, equipmentA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageEquipmentDocumentRecord)(carrierUser, equipmentA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageEquipmentDocumentRecord)(otherCarrierUser, equipmentA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageEquipmentDocumentRecord)(admin, { organizationId: orgB, carrierId: carrierB, equipmentId: "equipment-b" }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageEquipmentDocumentRecord)(carrierUser, equipmentA, false), false);
});
(0, node_test_1.default)("inspection reports are visible to org staff and linked carriers only", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    const inspectionA = { organizationId: orgA, carrierId: carrierA };
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(platform, { organizationId: orgB, carrierId: carrierB }, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(admin, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(staff, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(carrierUser, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(otherCarrierUser, inspectionA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(admin, { organizationId: orgB, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessInspectionRecord)(carrierUser, inspectionA, false), false);
});
(0, node_test_1.default)("inspection management is staff scoped while document upload allows linked carriers", () => {
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    const inspectionA = { organizationId: orgA, carrierId: carrierA };
    strict_1.default.equal((0, tenant_rules_1.canManageInspectionRecord)(admin, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageInspectionRecord)(staff, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageInspectionRecord)(carrierUser, inspectionA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadInspectionDocumentRecord)(admin, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadInspectionDocumentRecord)(staff, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadInspectionDocumentRecord)(carrierUser, inspectionA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadInspectionDocumentRecord)(otherCarrierUser, inspectionA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadInspectionDocumentRecord)(carrierUser, { organizationId: orgB, carrierId: carrierA }, true), false);
});
(0, node_test_1.default)("driver document permission allows admins, staff, and linked carriers only", () => {
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    const driverA = { organizationId: orgA, carrierId: carrierA, driverId: "driver-a" };
    strict_1.default.equal((0, tenant_rules_1.canManageDriverDocumentRecord)(admin, driverA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageDriverDocumentRecord)(staff, driverA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageDriverDocumentRecord)(carrierUser, driverA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageDriverDocumentRecord)(otherCarrierUser, driverA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageDriverDocumentRecord)(admin, { organizationId: orgB, carrierId: carrierB, driverId: "driver-b" }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageDriverDocumentRecord)(carrierUser, driverA, false), false);
});
(0, node_test_1.default)("admin and staff can only access carriers in their own active organization", () => {
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(admin, { organizationId: orgA, carrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(staff, { organizationId: orgA, carrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(admin, { organizationId: orgB, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(staff, { organizationId: orgB, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canMutateTenantRecord)(admin, orgA, ["admin"], true), true);
    strict_1.default.equal((0, tenant_rules_1.canMutateTenantRecord)(staff, orgA, ["admin"], true), false);
    strict_1.default.equal((0, tenant_rules_1.canMutateTenantRecord)(staff, orgA, ["admin", "staff"], true), true);
    strict_1.default.equal((0, tenant_rules_1.canMutateTenantRecord)(staff, orgA, ["admin", "staff"], false), false);
});
(0, node_test_1.default)("platform super admin can access carriers and mutate tenant records across organizations", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    strict_1.default.equal((0, tenant_rules_1.canAccessCarrierRecord)(platform, { organizationId: orgB, carrierId: carrierB }, false), true);
    strict_1.default.equal((0, tenant_rules_1.canMutateTenantRecord)(platform, orgB, ["admin"], false), true);
});
(0, node_test_1.default)("upload path validation accepts only the expected organization and carrier prefix", () => {
    const validPath = `organizations/${orgA}/carriers/${carrierA}/certificate-of-insurance/v1/file.pdf`;
    const wrongOrgPath = `organizations/${orgB}/carriers/${carrierA}/certificate-of-insurance/v1/file.pdf`;
    const wrongCarrierPath = `organizations/${orgA}/carriers/${carrierB}/certificate-of-insurance/v1/file.pdf`;
    const legacyPath = `carriers/${carrierA}/certificate-of-insurance/v1/file.pdf`;
    strict_1.default.equal((0, tenant_rules_1.isTenantStoragePath)(validPath, orgA, carrierA), true);
    strict_1.default.equal((0, tenant_rules_1.isTenantStoragePath)(wrongOrgPath, orgA, carrierA), false);
    strict_1.default.equal((0, tenant_rules_1.isTenantStoragePath)(wrongCarrierPath, orgA, carrierA), false);
    strict_1.default.equal((0, tenant_rules_1.isTenantStoragePath)(legacyPath, orgA, carrierA), false);
    strict_1.default.doesNotThrow(() => (0, tenant_rules_1.assertTenantStoragePath)(validPath, orgA, carrierA));
    strict_1.default.throws(() => (0, tenant_rules_1.assertTenantStoragePath)(wrongOrgPath, orgA, carrierA), /current organization/);
});
(0, node_test_1.default)("vehicle document storage path validation accepts only expected organization and equipment prefix", () => {
    const equipmentId = "equipment-a";
    const validPath = `organizations/${orgA}/equipment/${equipmentId}/registration/v1/file.pdf`;
    const wrongOrgPath = `organizations/${orgB}/equipment/${equipmentId}/registration/v1/file.pdf`;
    const wrongEquipmentPath = `organizations/${orgA}/equipment/equipment-b/registration/v1/file.pdf`;
    strict_1.default.equal((0, tenant_rules_1.isEquipmentDocumentStoragePath)(validPath, orgA, equipmentId), true);
    strict_1.default.equal((0, tenant_rules_1.isEquipmentDocumentStoragePath)(wrongOrgPath, orgA, equipmentId), false);
    strict_1.default.equal((0, tenant_rules_1.isEquipmentDocumentStoragePath)(wrongEquipmentPath, orgA, equipmentId), false);
    strict_1.default.doesNotThrow(() => (0, tenant_rules_1.assertEquipmentDocumentStoragePath)(validPath, orgA, equipmentId));
    strict_1.default.throws(() => (0, tenant_rules_1.assertEquipmentDocumentStoragePath)(wrongOrgPath, orgA, equipmentId), /current organization and equipment/);
});
(0, node_test_1.default)("inspection storage path validation accepts only expected organization and inspection prefix", () => {
    const inspectionId = "inspection-a";
    const validPath = `organizations/${orgA}/inspections/${inspectionId}/roadside/v1/file.pdf`;
    const wrongOrgPath = `organizations/${orgB}/inspections/${inspectionId}/roadside/v1/file.pdf`;
    const wrongInspectionPath = `organizations/${orgA}/inspections/inspection-b/roadside/v1/file.pdf`;
    strict_1.default.equal((0, tenant_rules_1.isInspectionStoragePath)(validPath, orgA, inspectionId), true);
    strict_1.default.equal((0, tenant_rules_1.isInspectionStoragePath)(wrongOrgPath, orgA, inspectionId), false);
    strict_1.default.equal((0, tenant_rules_1.isInspectionStoragePath)(wrongInspectionPath, orgA, inspectionId), false);
    strict_1.default.doesNotThrow(() => (0, tenant_rules_1.assertInspectionStoragePath)(validPath, orgA, inspectionId));
    strict_1.default.throws(() => (0, tenant_rules_1.assertInspectionStoragePath)(wrongOrgPath, orgA, inspectionId), /current organization and inspection/);
});
(0, node_test_1.default)("notification access is scoped by organization, assignment, and linked carrier", () => {
    const staff = session({ role: "staff", userId: "staff-a" });
    const carrierUser = session({ role: "carrier", userId: "carrier-user-a", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", userId: "carrier-user-b", carrierId: carrierB });
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(staff, { organizationId: orgA, carrierId: carrierA, assignedTo: null }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(staff, { organizationId: orgB, carrierId: carrierB, assignedTo: "staff-a" }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: carrierA, assignedTo: null }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(otherCarrierUser, { organizationId: orgA, carrierId: carrierA, assignedTo: null }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: null, assignedTo: "carrier-user-a", userId: null }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: null, assignedTo: null, userId: "carrier-user-a" }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: carrierA, assignedTo: null }, false), false);
});
(0, node_test_1.default)("compliance task access is scoped by organization, assignment, and linked carrier", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin", userId: "admin-a" });
    const staff = session({ role: "staff", userId: "staff-a" });
    const carrierUser = session({ role: "carrier", userId: "carrier-user-a", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", userId: "carrier-user-b", carrierId: carrierB });
    const carrierTask = { organizationId: orgA, relatedCarrierId: carrierA, assignedTo: null };
    const assignedTask = { organizationId: orgA, relatedCarrierId: null, assignedTo: "carrier-user-a" };
    const unassignedManualTask = { organizationId: orgA, relatedCarrierId: null, assignedTo: null };
    const otherCarrierTask = { organizationId: orgA, relatedCarrierId: carrierB, assignedTo: null };
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(platform, { organizationId: orgB, relatedCarrierId: carrierB, assignedTo: null }, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(admin, carrierTask, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(staff, carrierTask, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(admin, { organizationId: orgB, relatedCarrierId: carrierB, assignedTo: null }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(carrierUser, carrierTask, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(carrierUser, assignedTask, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(carrierUser, unassignedManualTask, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(carrierUser, otherCarrierTask, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(otherCarrierUser, carrierTask, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessComplianceTaskRecord)(carrierUser, carrierTask, false), false);
    strict_1.default.equal((0, tenant_rules_1.canManageComplianceTaskRecord)(admin, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageComplianceTaskRecord)(staff, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageComplianceTaskRecord)(carrierUser, orgA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageComplianceTaskRecord)(staff, orgB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageComplianceTaskRecord)(platform, orgB, false), true);
});
(0, node_test_1.default)("secure upload links are manageable only by platform, admin, and staff in the organization", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const uploadLink = { organizationId: orgA, carrierId: carrierA };
    strict_1.default.equal((0, tenant_rules_1.canAccessUploadLinkRecord)(platform, { organizationId: orgB, carrierId: carrierB }, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessUploadLinkRecord)(admin, uploadLink, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessUploadLinkRecord)(staff, uploadLink, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessUploadLinkRecord)(admin, { organizationId: orgB, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessUploadLinkRecord)(carrierUser, uploadLink, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageUploadLinkRecord)(staff, uploadLink, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageUploadLinkRecord)(carrierUser, uploadLink, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageUploadLinkRecord)(staff, uploadLink, false), false);
});
(0, node_test_1.default)("load access is scoped by organization, role, and linked carrier", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    const loadA = { organizationId: orgA, carrierId: carrierA };
    const loadB = { organizationId: orgB, carrierId: carrierB };
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(platform, loadB, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(admin, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(staff, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(admin, loadB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(otherCarrierUser, loadA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, loadA, false), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadTimeline)(carrierUser, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadTimeline)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadTimeline)(admin, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadTimeline)(platform, loadB, false), true);
    strict_1.default.equal((0, tenant_rules_1.canManageLoadRecord)(admin, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageLoadRecord)(staff, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageLoadRecord)(carrierUser, loadA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canCreateLoadRecord)(admin, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateLoadRecord)(staff, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateLoadRecord)(carrierUser, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateLoadRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canCreateLoadRecord)(carrierUser, { organizationId: orgB, carrierId: carrierA }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageLoadDocumentRecord)(carrierUser, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageLoadDocumentRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageLoadDocumentRecord)(carrierUser, { organizationId: orgB, carrierId: carrierA }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocument)(carrierUser, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocument)(otherCarrierUser, loadA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocumentType)(admin, loadA, "rate_confirmation", true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocumentType)(staff, loadA, "rate_confirmation", true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocumentType)(carrierUser, loadA, "rate_confirmation", true), true);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocumentType)(carrierUser, loadA, "pod", true), true);
    strict_1.default.equal((0, tenant_rules_1.canExportLoadArchive)(carrierUser, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canExportLoadArchive)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canExportOrganizationLoadArchive)(carrierUser, orgA), false);
    strict_1.default.equal((0, tenant_rules_1.canExportOrganizationLoadArchive)(staff, orgA), true);
    strict_1.default.equal((0, tenant_rules_1.canExportOrganizationLoadArchive)(admin, orgA), true);
    strict_1.default.equal((0, tenant_rules_1.canExportOrganizationLoadArchive)(platform, orgB), true);
    strict_1.default.equal((0, tenant_rules_1.canDeleteArchivedLoadFiles)(admin, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canDeleteArchivedLoadFiles)(staff, loadA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canDeleteArchivedLoadFiles)(carrierUser, loadA, true), false);
});
(0, node_test_1.default)("carrier direct load route attempts are blocked across carriers and organizations", () => {
    const carrierUser = session({ role: "carrier", carrierId: carrierA, organizationId: orgA });
    const sameOrgOtherCarrierLoad = { organizationId: orgA, carrierId: carrierB };
    const otherOrgSameCarrierIdLoad = { organizationId: orgB, carrierId: carrierA };
    const otherOrgOtherCarrierLoad = { organizationId: orgB, carrierId: carrierB };
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, sameOrgOtherCarrierLoad, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, otherOrgSameCarrierIdLoad, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, otherOrgOtherCarrierLoad, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocument)(carrierUser, sameOrgOtherCarrierLoad, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUploadLoadDocumentType)(carrierUser, sameOrgOtherCarrierLoad, "pod", true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadTimeline)(carrierUser, sameOrgOtherCarrierLoad, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadTimeline)(carrierUser, otherOrgSameCarrierIdLoad, true), false);
});
(0, node_test_1.default)("carrier-created load remains fetchable by linked carrier query scope", () => {
    const carrierUser = session({ role: "carrier", carrierId: carrierA, organizationId: orgA });
    const createdLoad = { organizationId: orgA, carrierId: carrierA };
    const scope = (0, tenant_rules_1.getLoadQueryScope)(carrierUser);
    strict_1.default.equal((0, tenant_rules_1.canCreateLoadRecord)(carrierUser, createdLoad, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessLoadRecord)(carrierUser, createdLoad, true), true);
    strict_1.default.deepEqual(scope, { organizationId: orgA, carrierId: carrierA });
});
(0, node_test_1.default)("load notification scoping blocks organization-wide and cross-carrier load alerts for carriers", () => {
    const admin = session({ role: "admin" });
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const carrierUser = session({ role: "carrier", userId: "carrier-user-a", carrierId: carrierA });
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: carrierA, assignedTo: null }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB, assignedTo: null }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(carrierUser, { organizationId: orgA, carrierId: null, assignedTo: null }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(admin, { organizationId: orgA, carrierId: null, assignedTo: null }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessNotificationRecord)(platform, { organizationId: orgB, carrierId: null, assignedTo: null }, false), true);
});
(0, node_test_1.default)("load document storage paths are scoped under organization and load", () => {
    const validPath = `organizations/${orgA}/loads/load-a/pod/v1/file.pdf`;
    const rateConPath = `organizations/${orgA}/loads/load-a/rate-confirmation/v1/file.pdf`;
    const wrongOrgPath = `organizations/${orgB}/loads/load-a/pod/v1/file.pdf`;
    const wrongLoadPath = `organizations/${orgA}/loads/load-b/pod/v1/file.pdf`;
    strict_1.default.equal((0, tenant_rules_1.isLoadStoragePath)(validPath, orgA, "load-a"), true);
    strict_1.default.equal((0, tenant_rules_1.isLoadStoragePath)(wrongOrgPath, orgA, "load-a"), false);
    strict_1.default.equal((0, tenant_rules_1.isLoadStoragePath)(wrongLoadPath, orgA, "load-a"), false);
    strict_1.default.equal((0, tenant_rules_1.isLoadDocumentStoragePath)(validPath, orgA, "load-a", "pod"), true);
    strict_1.default.equal((0, tenant_rules_1.isLoadDocumentStoragePath)(rateConPath, orgA, "load-a", "rate_confirmation"), true);
    strict_1.default.equal((0, tenant_rules_1.isLoadDocumentStoragePath)(validPath, orgA, "load-a", "rate_confirmation"), false);
});
(0, node_test_1.default)("invoice permissions preserve carrier and organization isolation", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    const invoiceA = { organizationId: orgA, carrierId: carrierA };
    const invoiceB = { organizationId: orgB, carrierId: carrierB };
    strict_1.default.equal((0, tenant_rules_1.canAccessInvoiceRecord)(platform, invoiceB, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInvoiceRecord)(admin, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInvoiceRecord)(staff, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInvoiceRecord)(carrierUser, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessInvoiceRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessInvoiceRecord)(otherCarrierUser, invoiceA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canGenerateInvoiceRecord)(carrierUser, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canGenerateInvoiceRecord)(carrierUser, { organizationId: orgA, carrierId: carrierB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canSendInvoiceRecord)(admin, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canSendInvoiceRecord)(carrierUser, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canSendInvoiceRecord)(otherCarrierUser, invoiceA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canUpdateInvoiceStatusRecord)(staff, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUpdateInvoiceStatusRecord)(carrierUser, invoiceA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canUpdateInvoiceStatusRecord)(carrierUser, invoiceA, false), false);
    strict_1.default.equal((0, tenant_rules_1.isInvoiceStoragePath)(`organizations/${orgA}/loads/load-a/invoices/v1/invoice.pdf`, orgA, "load-a"), true);
    strict_1.default.equal((0, tenant_rules_1.isInvoiceStoragePath)(`organizations/${orgB}/loads/load-a/invoices/v1/invoice.pdf`, orgA, "load-a"), false);
});
(0, node_test_1.default)("broker registry permissions preserve tenant and carrier request scope", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    const otherCarrierUser = session({ role: "carrier", carrierId: carrierB });
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(platform, { organizationId: orgB }, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(admin, { organizationId: orgA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(staff, { organizationId: orgA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(admin, { organizationId: orgB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(carrierUser, { organizationId: orgA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(carrierUser, { organizationId: orgB }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(carrierUser, { organizationId: orgA, linkedCarrierIds: [carrierA] }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(otherCarrierUser, { organizationId: orgA, linkedCarrierIds: [carrierA] }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(carrierUser, { organizationId: orgA, requestedByCarrierId: carrierA }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessBrokerRecord)(otherCarrierUser, { organizationId: orgA, requestedByCarrierId: carrierA }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageBrokerRecord)(admin, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageBrokerRecord)(staff, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageBrokerRecord)(carrierUser, orgA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageBrokerRecord)(platform, orgB, false), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateBrokerCheckRequest)(admin, orgA, null, true), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateBrokerCheckRequest)(staff, orgA, null, true), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateBrokerCheckRequest)(carrierUser, orgA, carrierA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canCreateBrokerCheckRequest)(carrierUser, orgA, carrierB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canCreateBrokerCheckRequest)(carrierUser, orgB, carrierA, true), false);
});
(0, node_test_1.default)("organization user management permissions preserve tenant and role boundaries", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    strict_1.default.equal((0, tenant_rules_1.canViewOrganizationUsers)(platform, orgB, false), true);
    strict_1.default.equal((0, tenant_rules_1.canViewOrganizationUsers)(admin, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canViewOrganizationUsers)(staff, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canViewOrganizationUsers)(carrierUser, orgA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canViewOrganizationUsers)(admin, orgB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canInviteOrganizationUsers)(admin, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canInviteOrganizationUsers)(staff, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canInviteOrganizationUsers)(carrierUser, orgA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canInviteOrganizationUsers)(staff, orgB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageOrganizationUsers)(admin, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canManageOrganizationUsers)(staff, orgA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageOrganizationUsers)(carrierUser, orgA, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageOrganizationUsers)(admin, orgB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canManageOrganizationUsers)(platform, orgB, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAssignCarrierToUser)(admin, orgA, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAssignCarrierToUser)(staff, orgA, orgA, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAssignCarrierToUser)(admin, orgA, orgB, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAssignCarrierToUser)(carrierUser, orgA, orgA, true), false);
});
(0, node_test_1.default)("audit log access is scoped by platform, organization, and role sensitivity", () => {
    const platform = session({ role: "admin", organizationId: null, platformSuperAdmin: true });
    const admin = session({ role: "admin" });
    const staff = session({ role: "staff" });
    const carrierUser = session({ role: "carrier", carrierId: carrierA });
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(platform, { organizationId: orgB, action: "organization.suspended" }, false), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(admin, { organizationId: orgA, action: "user.role_changed" }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(admin, { organizationId: orgB, action: "carrier.created" }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(staff, { organizationId: orgA, action: "carrier.status_changed" }, true), true);
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(staff, { organizationId: orgA, action: "user.role_changed" }, true), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(staff, { organizationId: orgA, action: "carrier.created" }, false), false);
    strict_1.default.equal((0, tenant_rules_1.canAccessAuditLogRecord)(carrierUser, { organizationId: orgA, action: "carrier.created" }, true), false);
});
